### ISSUE TITLE
unknown field 'Show' in struct literal of type chart.Style

### ISSUE THREAD

**Issue by Azanul** [muesli/silhouette#1]
Unable to go get it

# github.com/muesli/silhouette
C:\Users\hp\go\src\github.com\muesli\silhouette\silhouette.go:97:5: unknown field 'Show' in struct literal of type chart.Style
C:\Users\hp\go\src\github.com\muesli\silhouette\silhouette.go:113:5: unknown field 'Show' in struct literal of type chart.Style
C:\Users\hp\go\src\github.com\muesli\silhouette\silhouette.go:118:5: unknown field 'Show' in struct literal of type chart.Style

go version **go1.13.5** windows/amd64

**Comment by muesli** [comment]
Make sure to enable Go Modules to use the pinned dependencies with the right version.

**Comment by Azanul** [comment]
As of Go 1.13, the go command by default downloads and authenticates modules using the Go module mirror and Go checksum database run by Google.

**Comment by muesli** [comment]
Almost correct: it only does so if either `GO111MODULE` is set to `on` or it finds a `go.mod` file in the current working dir. You can enforce it by running:

```
GO111MODULE="on" go get github.com/muesli/silhouette
```

Hope this helps!

**Comment by Azanul** [comment]
This
`GO111MODULE="on" go get github.com/muesli/silhouette`
gives error that
GO111MODULE=on : The term 'GO111MODULE=on' is not recognized as the name of a cmdlet, function, script file, or operable program.

Did this instead
`go env -w GO111MODULE="on"
go get github.com/muesli/silhouette`
still same issue

**Comment by muesli** [comment]
Sorry, on Windows you'll probably have to do something like:

```
set GO111MODULE=on
go get github.com/muesli/silhouette
```

GO111MODULE isn't a supported `go env` parameter if I remember correctly.

**Comment by Azanul** [comment]
Problem persists
BTW, I am working on VScode with Go Modules enabled.
